apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppdm-cli
  labels:
    app: ppdm-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ppdm-cli
  template:
    metadata:
      labels:
        app: ppdm-cli
    spec:
      containers:
      - name: ppdm-cli
        image: quay.io/delldps/ppdm-cli:20.1.0.0-9
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "20.1.0.0-9"
